FROM debian:wheezy

#Default branch name develop
ARG BRANCH_NAME=develop
#Default
ARG REPO_SLUG=vcore/vcore
ENV REPO_SLUG=${REPO_SLUG}
ENV REPO_URL=https://github.com/${REPO_SLUG}

RUN apt-get -qq update && \
    apt-get -qqy install \
    git \
    sudo

#RUN git clone ${REPO_URL} --branch $BRANCH_NAME --single-branch --depth 1

COPY vcore.tar.gz /vcore.tar.gz
RUN tar -xvf /vcore.tar.gz

#ADD . /vcore
RUN cd /vcore/scripts/windows-crosscompile && ./dependencies.sh
RUN cd /vcore && scripts/windows-crosscompile/compile-vcore.sh