.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. vcore_qt test_vcore_qt
clean: FORCE
	$(MAKE) -C .. vcore_qt_clean test_vcore_qt_clean
check: FORCE
	$(MAKE) -C .. test_vcore_qt_check
vcore-qt vcore-qt.exe: FORCE
	 $(MAKE) -C .. vcore_qt